# In this file you define the beacons that are placed in your environment and used for the Indoor Positioning System.
# The positioning node will return the the information of the closest beacon, so you can use it in your application.

# You have to specify the EID of each beacon you want to use, so the positioning system can recognize them.
# The other values are optional and defaults will be used if they are unspecified.

# beacon template:
# EID: 0123456789ABCDEF     # this is the beacon's unique Extended ID (EID) and is hardcoded to the device
#   name: first_beacon      # arbitrary label for identification of the beacon, default: <EID>
#   position: 1 2 3         # position of the beacon in your environment, specified by X Y Z values, default: 0 0 0
#   frame_id: map           # name of the coordinate frame the position is related to, default: map

# example beacon
beacon0:
  EID: 0123456789ABCDEF
  name: beaconname
  zone: zone0
  frame_id: map
  position: 1 1 1

# example zone
zone0:
  name: zonename
  frame_id: map
  polygon: [x1, y1, z1,
            x2, y2, z2,
            x3, y3, z3]